//
//  Stub.swift
//  Mockable
//
//  Created by Daniel Cardona on 4/07/25.
//

/// A ``Stub`` is a test double that provides pre-canned answers to method calls.
///
/// You use stubs to control the behavior of a dependency during a test. For example, you can stub a method to return a specific value, or to throw an error.
/// Stubs are created by calling the `when(calledWith:)` method on a ``Spy``.
///
/// ### Usage Example:
///
/// ```swift
/// protocol MyService {
///     func fetchData(id: String) -> String
///     func calculate(a: Int, b: Int) throws -> Int
/// }
///
/// // Assuming MyServiceMock is generated by @Mockable macro
/// let mock = MyServiceMock()
/// let spy = mock.context // Access the spy instance
///
/// // Stub fetchData to return "mockedData" when called with "testId"
/// spy.fetchData.when(calledWith: .equal("testId")).thenReturn("mockedData")
///
/// // Stub calculate to throw an error when called with specific arguments
/// spy.calculate.when(calledWith: .equal(0), .any).thenThrow(MyError.invalidInput)
///
/// // Now, when you call these methods on the mock, they will behave as stubbed:
/// let data = mock.fetchData(id: "testId") // data will be "mockedData"
/// do {
///     _ = try mock.calculate(a: 0, b: 5) // This will throw MyError.invalidInput
/// } catch { /* handle error */ }
/// ```
public class Stub<each I, Effects: Effect, O> {
    /// The ``InvocationMatcher`` that defines when this stub should be applied.
    public let invocationMatcher: InvocationMatcher<repeat each I>
    var output: ((Invocation<repeat each I>) -> Return<O>)?

    /// Initializes a `Stub` instance.
    /// - Parameter invocationMatcher: The ``InvocationMatcher`` that determines when this stub is active.
    init( invocationMatcher: InvocationMatcher<repeat each I>) {
        self.invocationMatcher = invocationMatcher
    }

    func returnValue(for invocation: Invocation<repeat each I>) -> Return<O>? {
        guard invocationMatcher.isMatchedBy(invocation) else {
            return nil
        }
        return output?(invocation)

    }

    /// Defines the return value for this stub.
    /// - Parameter output: The value to return when this stub is matched.
    public func thenReturn(_ output: O) {
        self.output = { _ in  Return.value(output) }
    }

    public func thenReturn(_ handler: @escaping (repeat each I) -> O) {
        self.output = { invocation in
            let returnValue = handler(repeat each invocation.arguments)
            return Return.value(returnValue)
        }

    }
}

extension Stub where Effects: Throwing {
    /// Defines an error to be thrown when this stub is matched.
    /// - Parameter error: The error to throw.
    public func thenThrow<E: Error>(_ error: E) {
        self.output = { _ in  Return.error(error) }
    }
}
