// Generated by the @Mockable macro — you never write this yourself.
#if DEBUG
class MockPricingService: Mock, @unchecked Sendable, PricingService {
    func price(for item: ArgMatcher<String>) -> Interaction<String, None, Int> {
        Interaction(item, spy: super.price)
    }
    func price(for item: String) -> Int {
        return adapt(super.price, item)
    }
}
#endif
