//
//  MockitoTests.swift
//  Mockable
//
//  Created by Daniel Cardona on 7/07/25.
//

import Mockable
import XCTest

final class MockitoTests: XCTestCase {
    func testMock() {
        let mock = PricingServiceMock.new()
        let spy = mock.context
        let store = Store(pricingService: mock)
        spy.price.when(calledWith:.equal("apple")).thenReturn(100)
        spy.price.when(calledWith:.equal("banana")).thenReturn(100)
        store.items = ["apple", "banana"]
        store.tagPrices()
        when(spy.price(.any)).thenReturn(100)
        XCTAssert(spy.price.verify(calledWith: .any, count: .equal(2)))
    }

    func testMockitoBuilder() {
        let mock = PricingServiceMock.new()
        let spy = mock.context
        let store = Store(pricingService: mock)
        when(spy.price("apple")).thenReturn(13)
        when(spy.price("banana")).thenReturn(17)

        store.register("apple")
        store.register("banana")
        verify(spy.price(.any)).called(2)
        XCTAssertEqual(store.prices["apple"], 13)
        XCTAssertEqual(store.prices["banana"], 17)
    }
}

class Store {
    var items: [String] = []
    var prices: [String: Int] =  [:]
    let pricingService: any PricingService
    init<Service: PricingService>(pricingService: Service) {
        self.pricingService = pricingService
    }

    func register(_ item: String) {
        items.append(item)
        let price = pricingService.price(item)
        prices[item] = price
    }

    func tagPrices() {
        for item in items {
            let price = pricingService.price(item)
            prices[item] = price
        }
    }
}

@Mockable
protocol PricingService {
    func price(_ item: String) -> Int
}

// This would be generated by the Witnessed macro
struct PricingServiceWitness<A> {
    var price: (A, String) -> Int

    struct Synthesized: PricingService {
        let context: A
        let witness: PricingServiceWitness

        func price(_ item: String) -> Int {
            witness.price(context, item)
        }
    }
}
